### ISSUE TITLE
IDAIpython crash on IDA 6.9 Service Pack 1 - Windows 7

### ISSUE THREAD

**Issue by dummys** [james91b/ida_ipython#28]
Hello,

Was working in 6.8 but after upgrading in 6.9 then 6.9 SP1 got this error:

Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 6.9\python\ipythonEmbed.py", line 19, in <module>
    from ipykernel.kernelapp import IPKernelApp
ImportError: No module named ipykernel.kernelapp
A Python Error Occurred trying to start the kernel!
alleycat.py: Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 6.9\python\idaapi.py", line 589, in IDAPython_ExecScript
    scriptpath = os.path.dirname(script)
  File "C:\Anaconda\Lib\ntpath.py", line 177, in dirname
    return split(p)[0]
  File "C:\Anaconda\Lib\ntpath.py", line 150, in split
    while head2 and head2[-1] in '/\':
AttributeError: 'module' object has no attribute 'start'

Can you fix it ? Thanks a lot.
Love your plugins, can't work anymore without it.

**Comment by tmr232** [comment]
Just to be on the safe side - are IDA and IDAPython running properly?

**Comment by dummys** [comment]
yes

**Comment by tmr232** [comment]
Well then, I'll try looking into it soon.

**Comment by dummys** [comment]
tell me if you need more information.

**Comment by tmr232** [comment]
Well, for one thing, the traceback looks weird. 
The exception seems to have nothing to do with the line displayed. 
Any chance the code changed during runtime?

**Comment by dummys** [comment]
I tried without other plugins,  same error.

**Comment by dummys** [comment]
Its sn offline computer,  ipython hasent been updated for a while...  could
be the issue?

**Comment by tmr232** [comment]
I don't know. It's probably worth checking.

**Comment by tmr232** [comment]
Ok. I just tested it on Windows 7 SP1 x64.
Latest IDA, latest IPython. Everything worked, couldn't reproduce the bug.

Which release of IDA IPython are you using? You need 0.4 for IDA 6.9 support.
I suggest you update both IPython and IDA IPython to latest versions and see if it solves it.

**Comment by dummys** [comment]
Updated to Anaconda to 2.5.0 x32, it worked yes :) Thanks
